name: Hello World Workflow

on: 
 # This workflow runs every time a push is made to the repository
  push:
     branches: ["main"]
jobs:
  say-hello: # Name of the job
    runs-on: ubuntu-latest # The job runs on the latest version of an Ubuntu virtual machine
    steps:
      - name: Greet the world # Name of the step
        run: echo "Hello, World!" # Command to run in the shell
      - name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
        # You may pin to the exact commit or the version.
        # uses: ArtificialAmateur/cpp-linter-action@6281cc1ef3abe25ee492f19f7d8b184ca873db34
        uses: ArtificialAmateur/cpp-linter-action@0.01
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # For 'with'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For 'env'
